### ISSUE TITLE
So this is a work in progress right?

### ISSUE THREAD

**Issue by KingWalnut** [ESX-Brasil/esx_prisonjob#2]
So I am wondering if there is suppose to be a client file as well? Whenever you adjust the coords for POS, nothing shows up?

**Comment by psycodeliccircus** [comment]
configure these lines in the "jobs/electrician.lua" folder and files
```lua
        Generator = {
            Pos   = {x = X_HERE, y = Y_HERE, z = Z_HERE},
			
		Delivery = {
            Pos   = {x = X_HERE, y = Y_HERE, z = Z_HERE},
```
@KingWalnut

**Comment by KingWalnut** [comment]
> configure these lines in the "jobs/electrician.lua" folder and files
> 
> ```lua
>         Generator = {
>             Pos   = {x = X_HERE, y = Y_HERE, z = Z_HERE},
> 			
> 		Delivery = {
>             Pos   = {x = X_HERE, y = Y_HERE, z = Z_HERE},
> ```
> 
> @KingWalnut

I do but nothing shows up when I do this, no blips nothing.

**Comment by psycodeliccircus** [comment]
![bc62bab1a5d0eb868a879e475839d0d4ec465e7d_2_100x100](https://user-images.githubusercontent.com/2183646/57739875-9a229480-768b-11e9-8ebb-6c05361f5a78.jpg)
![93b40db164a82205b819120778abfe8eed1ba85f](https://user-images.githubusercontent.com/2183646/57739888-a27acf80-768b-11e9-8bb3-55c79763eeaa.png)

**Comment by KingWalnut** [comment]
Mmm I will try tonight again and get back to you

**Comment by psycodeliccircus** [comment]
ok :)

**Comment by ElReyDeCabra** [comment]
Having an issue to where its not working for me. I have tried multiple different times to get it to work added both sql and changed the coords and have tried to move it to multiple locations. Could you list which jail system you are using maybe thats why it isnt working.
